package com.codetrimmer.service;

import com.codetrimmer.error.CodeTrimmerException;
import com.codetrimmer.error.ErrorCode;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.attribute.PosixFilePermission;
import java.util.Set;

/**
 * Service for generating Git pre-commit hooks.
 * Supports Windows (batch/PowerShell) and Unix (bash) platforms.
 */
@Service
public class HookGenerator {

    private static final Logger LOGGER = LoggerFactory.getLogger(HookGenerator.class);

    /**
     * Generates a pre-commit hook for the specified directory.
     *
     * @param directory the project directory containing .git folder
     * @param force if true, overwrite existing hook
     * @return the path to the generated hook
     */
    public Path generatePreCommitHook(String directory, boolean force) {
        Path projectPath = Paths.get(directory);
        Path gitDir = projectPath.resolve(".git");

        if (!Files.exists(gitDir)) {
            throw new CodeTrimmerException(
                ErrorCode.CT_0051,
                "No .git directory found in: " + directory,
                "Run this command from a Git repository root"
            );
        }

        Path hooksDir = gitDir.resolve("hooks");
        try {
            Files.createDirectories(hooksDir);
        } catch (IOException e) {
            throw new CodeTrimmerException(ErrorCode.CT_0050, e);
        }

        Path hookPath = hooksDir.resolve("pre-commit");
        if (Files.exists(hookPath) && !force) {
            throw new CodeTrimmerException(
                ErrorCode.CT_0052,
                "Hook already exists: " + hookPath,
                "Use --force to overwrite existing hook"
            );
        }

        try {
            String hookContent = generateBashHook();
            Files.writeString(hookPath, hookContent);
            makeExecutable(hookPath);
            LOGGER.info("Pre-commit hook generated: {}", hookPath);

            // Also generate Windows batch file
            generateWindowsHooks(hooksDir, force);

            return hookPath;
        } catch (IOException e) {
            throw new CodeTrimmerException(ErrorCode.CT_0050, e);
        }
    }

    /**
     * Generates bash pre-commit hook content.
     *
     * @return the hook script content
     */
    private String generateBashHook() {
        return """
            #!/bin/bash
            # Code Trimmer Pre-commit Hook
            # Generated by Code Trimmer
            # https://github.com/pbaletkeman/codeTrimmer

            set -e

            echo "Running Code Trimmer on staged files..."

            # Get list of staged files (excluding deleted files)
            STAGED_FILES=$(git diff --cached --name-only --diff-filter=d)

            if [ -z "$STAGED_FILES" ]; then
                echo "No files to process"
                exit 0
            fi

            # Check if Code Trimmer JAR exists
            TRIMMER_JAR="${CODE_TRIMMER_JAR:-code-trimmer.jar}"
            if [ ! -f "$TRIMMER_JAR" ]; then
                # Try common locations
                if [ -f "./target/code-trimmer-1.0.0.jar" ]; then
                    TRIMMER_JAR="./target/code-trimmer-1.0.0.jar"
                elif [ -f "./code-trimmer.jar" ]; then
                    TRIMMER_JAR="./code-trimmer.jar"
                else
                    echo "Warning: Code Trimmer JAR not found. Skipping whitespace check."
                    echo "Set CODE_TRIMMER_JAR environment variable or place JAR in project root."
                    exit 0
                fi
            fi

            # Create a temporary file list
            TEMP_FILE=$(mktemp)
            echo "$STAGED_FILES" > "$TEMP_FILE"

            # Run Code Trimmer in dry-run mode to check for changes
            NEEDS_TRIMMING=0
            while IFS= read -r file; do
                if [ -f "$file" ]; then
                    java -jar "$TRIMMER_JAR" trim "$file" --dry-run --quiet 2>/dev/null
                    if [ $? -eq 0 ]; then
                        # Check if file would be modified
                        OUTPUT=$(java -jar "$TRIMMER_JAR" trim "$file" --dry-run 2>&1)
                        if echo "$OUTPUT" | grep -q "Files modified: [1-9]"; then
                            NEEDS_TRIMMING=1
                            echo "  File needs trimming: $file"
                        fi
                    fi
                fi
            done < "$TEMP_FILE"

            rm -f "$TEMP_FILE"

            if [ $NEEDS_TRIMMING -eq 1 ]; then
                echo ""
                echo "Some files need whitespace cleanup."
                echo "Run 'java -jar $TRIMMER_JAR trim .' to fix them."
                exit 1
            fi

            echo "All files pass whitespace checks."
            exit 0
            """;
    }

    /**
     * Generates Windows hook files.
     *
     * @param hooksDir the hooks directory
     * @param force if true, overwrite existing hooks
     */
    private void generateWindowsHooks(Path hooksDir, boolean force) throws IOException {
        // Generate batch file
        Path batchPath = hooksDir.resolve("pre-commit.bat");
        if (!Files.exists(batchPath) || force) {
            Files.writeString(batchPath, generateBatchHook());
            LOGGER.info("Windows batch hook generated: {}", batchPath);
        }

        // Generate PowerShell script
        Path ps1Path = hooksDir.resolve("pre-commit.ps1");
        if (!Files.exists(ps1Path) || force) {
            Files.writeString(ps1Path, generatePowerShellHook());
            LOGGER.info("PowerShell hook generated: {}", ps1Path);
        }
    }

    /**
     * Generates Windows batch pre-commit hook content.
     *
     * @return the batch script content
     */
    private String generateBatchHook() {
        return """
            @echo off
            REM Code Trimmer Pre-commit Hook
            REM Generated by Code Trimmer

            echo Running Code Trimmer on staged files...

            REM Check if Code Trimmer JAR exists
            set TRIMMER_JAR=code-trimmer.jar
            if exist target\\code-trimmer-1.0.0.jar (
                set TRIMMER_JAR=target\\code-trimmer-1.0.0.jar
            )

            if not exist "%TRIMMER_JAR%" (
                echo Warning: Code Trimmer JAR not found. Skipping whitespace check.
                exit /b 0
            )

            REM Get staged files
            for /f "delims=" %%f in ('git diff --cached --name-only --diff-filter=d') do (
                if exist "%%f" (
                    java -jar "%TRIMMER_JAR%" trim "%%f" --dry-run --quiet
                )
            )

            echo All files pass whitespace checks.
            exit /b 0
            """;
    }

    /**
     * Generates PowerShell pre-commit hook content.
     *
     * @return the PowerShell script content
     */
    private String generatePowerShellHook() {
        return """
            # Code Trimmer Pre-commit Hook
            # Generated by Code Trimmer

            Write-Host "Running Code Trimmer on staged files..."

            # Check if Code Trimmer JAR exists
            $TrimmerJar = "code-trimmer.jar"
            if (Test-Path "target\\code-trimmer-1.0.0.jar") {
                $TrimmerJar = "target\\code-trimmer-1.0.0.jar"
            }

            if (-not (Test-Path $TrimmerJar)) {
                Write-Host "Warning: Code Trimmer JAR not found. Skipping whitespace check."
                exit 0
            }

            # Get staged files
            $stagedFiles = git diff --cached --name-only --diff-filter=d
            $needsTrimming = $false

            foreach ($file in $stagedFiles) {
                if (Test-Path $file) {
                    $output = java -jar $TrimmerJar trim $file --dry-run 2>&1
                    if ($output -match "Files modified: [1-9]") {
                        $needsTrimming = $true
                        Write-Host "  File needs trimming: $file"
                    }
                }
            }

            if ($needsTrimming) {
                Write-Host ""
                Write-Host "Some files need whitespace cleanup."
                Write-Host "Run 'java -jar $TrimmerJar trim .' to fix them."
                exit 1
            }

            Write-Host "All files pass whitespace checks."
            exit 0
            """;
    }

    /**
     * Makes a file executable on Unix systems.
     *
     * @param path the file path
     */
    private void makeExecutable(Path path) throws IOException {
        try {
            Set<PosixFilePermission> perms = Files.getPosixFilePermissions(path);
            perms.add(PosixFilePermission.OWNER_EXECUTE);
            perms.add(PosixFilePermission.GROUP_EXECUTE);
            perms.add(PosixFilePermission.OTHERS_EXECUTE);
            Files.setPosixFilePermissions(path, perms);
        } catch (UnsupportedOperationException e) {
            // Windows doesn't support POSIX permissions
            LOGGER.debug("POSIX permissions not supported on this platform");
        }
    }
}
