"""Git pre-commit hook generator service."""

import logging
import stat
from pathlib import Path

from codetrimmer.error.codes import ErrorCode
from codetrimmer.error.exceptions import CodeTrimmerException

logger = logging.getLogger(__name__)


class HookGenerator:
    """Service for generating Git pre-commit hooks.

    Supports Windows (batch/PowerShell) and Unix (bash) platforms.
    """

    def generate_pre_commit_hook(
        self,
        directory: str,
        force: bool = False,
    ) -> Path:
        """Generate a pre-commit hook for the specified directory.

        Args:
            directory: Project directory containing .git folder
            force: If True, overwrite existing hook

        Returns:
            Path to the generated hook

        Raises:
            CodeTrimmerException: If hook generation fails
        """
        project_path = Path(directory)
        git_dir = project_path / ".git"

        if not git_dir.exists():
            raise CodeTrimmerException(
                ErrorCode.CT_0051,
                f"No .git directory found in: {directory}",
                "Run this command from a Git repository root",
            )

        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir(parents=True, exist_ok=True)

        hook_path = hooks_dir / "pre-commit"
        if hook_path.exists() and not force:
            raise CodeTrimmerException(
                ErrorCode.CT_0052,
                f"Hook already exists: {hook_path}",
                "Use --force to overwrite existing hook",
            )

        try:
            hook_content = self._generate_bash_hook()
            hook_path.write_text(hook_content, encoding="utf-8")
            self._make_executable(hook_path)
            logger.info("Pre-commit hook generated: %s", hook_path)

            # Also generate Windows hooks
            self._generate_windows_hooks(hooks_dir, force)

            return hook_path

        except IOError as e:
            raise CodeTrimmerException(
                ErrorCode.CT_0050,
                f"Failed to generate hook: {e}",
                "Check disk space and permissions",
            ) from e

    def _generate_bash_hook(self) -> str:
        """Generate bash pre-commit hook content.

        Returns:
            Hook script content
        """
        return '''#!/bin/bash
# Code Trimmer Pre-commit Hook
# Generated by Code Trimmer
# https://github.com/pbaletkeman/code-trimmer-python

set -e

echo "Running Code Trimmer on staged files..."

# Get list of staged files (excluding deleted files)
STAGED_FILES=$(git diff --cached --name-only --diff-filter=d)

if [ -z "$STAGED_FILES" ]; then
    echo "No files to process"
    exit 0
fi

# Check if codetrimmer is installed
if ! command -v codetrimmer &> /dev/null; then
    echo "Warning: codetrimmer not found. Skipping whitespace check."
    echo "Install with: pip install codetrimmer"
    exit 0
fi

# Run Code Trimmer in dry-run mode to check for changes
NEEDS_TRIMMING=0
while IFS= read -r file; do
    if [ -f "$file" ]; then
        OUTPUT=$(codetrimmer trim "$file" --dry-run 2>&1)
        if echo "$OUTPUT" | grep -q "Files modified: [1-9]"; then
            NEEDS_TRIMMING=1
            echo "  File needs trimming: $file"
        fi
    fi
done <<< "$STAGED_FILES"

if [ $NEEDS_TRIMMING -eq 1 ]; then
    echo ""
    echo "Some files need whitespace cleanup."
    echo "Run 'codetrimmer trim .' to fix them."
    exit 1
fi

echo "All files pass whitespace checks."
exit 0
'''

    def _generate_windows_hooks(self, hooks_dir: Path, force: bool) -> None:
        """Generate Windows hook files.

        Args:
            hooks_dir: Hooks directory
            force: If True, overwrite existing hooks
        """
        # Generate batch file
        batch_path = hooks_dir / "pre-commit.bat"
        if not batch_path.exists() or force:
            batch_path.write_text(self._generate_batch_hook(), encoding="utf-8")
            logger.info("Windows batch hook generated: %s", batch_path)

        # Generate PowerShell script
        ps1_path = hooks_dir / "pre-commit.ps1"
        if not ps1_path.exists() or force:
            ps1_path.write_text(self._generate_powershell_hook(), encoding="utf-8")
            logger.info("PowerShell hook generated: %s", ps1_path)

    def _generate_batch_hook(self) -> str:
        """Generate Windows batch pre-commit hook content.

        Returns:
            Batch script content
        """
        return '''@echo off
REM Code Trimmer Pre-commit Hook
REM Generated by Code Trimmer

echo Running Code Trimmer on staged files...

REM Check if codetrimmer is installed
where codetrimmer >nul 2>nul
if %errorlevel% neq 0 (
    echo Warning: codetrimmer not found. Skipping whitespace check.
    echo Install with: pip install codetrimmer
    exit /b 0
)

REM Get staged files
for /f "delims=" %%f in ('git diff --cached --name-only --diff-filter=d') do (
    if exist "%%f" (
        codetrimmer trim "%%f" --dry-run --quiet
    )
)

echo All files pass whitespace checks.
exit /b 0
'''

    def _generate_powershell_hook(self) -> str:
        """Generate PowerShell pre-commit hook content.

        Returns:
            PowerShell script content
        """
        return '''# Code Trimmer Pre-commit Hook
# Generated by Code Trimmer

Write-Host "Running Code Trimmer on staged files..."

# Check if codetrimmer is installed
$codetrimmer = Get-Command codetrimmer -ErrorAction SilentlyContinue
if (-not $codetrimmer) {
    Write-Host "Warning: codetrimmer not found. Skipping whitespace check."
    Write-Host "Install with: pip install codetrimmer"
    exit 0
}

# Get staged files
$stagedFiles = git diff --cached --name-only --diff-filter=d
$needsTrimming = $false

foreach ($file in $stagedFiles) {
    if (Test-Path $file) {
        $output = codetrimmer trim $file --dry-run 2>&1
        if ($output -match "Files modified: [1-9]") {
            $needsTrimming = $true
            Write-Host "  File needs trimming: $file"
        }
    }
}

if ($needsTrimming) {
    Write-Host ""
    Write-Host "Some files need whitespace cleanup."
    Write-Host "Run 'codetrimmer trim .' to fix them."
    exit 1
}

Write-Host "All files pass whitespace checks."
exit 0
'''

    def _make_executable(self, path: Path) -> None:
        """Make a file executable on Unix systems.

        Args:
            path: File path
        """
        try:
            current_mode = path.stat().st_mode
            path.chmod(current_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        except OSError:
            # Windows doesn't support executable bit
            logger.debug("Could not set executable bit on %s", path)
